CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY,
    civil_id VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);